/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * MainFrame.java
 *
 * Created on May 5, 2011, 7:26:51 PM
 */
package client;

import java.awt.Dimension;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.awt.event.MouseAdapter;
import java.awt.event.MouseEvent;
import java.awt.event.WindowAdapter;
import java.awt.event.WindowEvent;

import javax.swing.JFrame;
import javax.swing.Timer;

/**
 * 
 * @author Brian
 */
public class MainFrame extends javax.swing.JFrame implements ActionListener {
	
	static boolean frozen = true;
	static Timer timer;
	static AnimationPane theAnimationPane;
	TPane theT;
	boolean run = false;

	/** Creates new form MainFrame */
	public MainFrame() {
		
		int fps = 0;

		// How many milliseconds between frames?
		int delay = (fps > 0) ? (1000 / fps) : 100;

		// Set up a timer that calls this object's action handler.
		timer = new Timer(delay, this);
		timer.setInitialDelay(0);
		timer.setCoalesce(true);
		timer.stop();
	}

	/**
	 * This method is called from within the constructor to initialize the form.
	 * WARNING: Do NOT modify this code. The content of this method is always
	 * regenerated by the Form Editor.
	 */
	@SuppressWarnings("unchecked")
	// <editor-fold defaultstate="collapsed"
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

		
		jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        BlueEdit = new javax.swing.JTextField();
        RedEdit = new javax.swing.JTextField();
        WhiteEdit = new javax.swing.JTextField();
        CyanEdit = new javax.swing.JTextField();
        YellowEdit = new javax.swing.JTextField();
        GreenEdit = new javax.swing.JTextField();
        OrangeEdit = new javax.swing.JTextField();
        PinkEdit = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        int arr[] = new int[15];
        for(int i=0;i<15;i++) {
        	arr[i] = i-7;
        }
        BlueEdit.setText(""+arr[(int)(Math.random()*15)]);

        RedEdit.setText(""+arr[(int)(Math.random()*15)]);

        WhiteEdit.setText(""+arr[(int)(Math.random()*15)]);

        CyanEdit.setText(""+arr[(int)(Math.random()*15)]);

        YellowEdit.setText(""+arr[(int)(Math.random()*15)]);

        GreenEdit.setText(""+arr[(int)(Math.random()*15)]);

        OrangeEdit.setText(""+arr[(int)(Math.random()*15)]);

        PinkEdit.setText(""+arr[(int)(Math.random()*15)]);
        theTPane = new TPane();
        theAnimationPane = new AnimationPane(this);
        

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        theTPane.setBackground(new java.awt.Color(153, 153, 153));

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(theTPane);
        theTPane.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 573, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 715, Short.MAX_VALUE)
        );

        theAnimationPane.setBackground(new java.awt.Color(102, 102, 102));

        jButton1.setText("Start");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton2.setText("Pause");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jButton3.setText("Generate Random Speeds");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Speeds");

        jLabel2.setForeground(new java.awt.Color(0, 255, 0));
        jLabel2.setText("Green");

        jLabel3.setForeground(java.awt.Color.yellow);
        jLabel3.setText("Yellow");

        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("White");

        jLabel5.setForeground(java.awt.Color.pink);
        jLabel5.setText("Pink");

        jLabel6.setForeground(new java.awt.Color(0, 0, 255));
        jLabel6.setText("Blue");

        jLabel7.setForeground(java.awt.Color.cyan);
        jLabel7.setText("Cyan");

        jLabel8.setForeground(java.awt.Color.orange);
        jLabel8.setText("Orange");

        jLabel9.setForeground(new java.awt.Color(255, 0, 0));
        jLabel9.setText("Red");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(theAnimationPane);
        theAnimationPane.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(57, 57, 57)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jButton1)
                        .addGap(30, 30, 30)
                        .addComponent(jButton2)
                        .addGap(32, 32, 32)
                        .addComponent(jButton3))
                    .addComponent(jLabel1)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(RedEdit, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel9))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel6)
                            .addComponent(BlueEdit, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2)
                            .addComponent(GreenEdit, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel3)
                            .addComponent(YellowEdit, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel4)
                            .addComponent(WhiteEdit, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel7)
                            .addComponent(CyanEdit, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(PinkEdit, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel5))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel8, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(OrangeEdit, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(111, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(598, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton1)
                    .addComponent(jButton2)
                    .addComponent(jButton3))
                .addGap(18, 18, 18)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(jLabel7)
                    .addComponent(jLabel8)
                    .addComponent(jLabel4)
                    .addComponent(jLabel3)
                    .addComponent(jLabel2)
                    .addComponent(jLabel6)
                    .addComponent(jLabel9))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(OrangeEdit, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(PinkEdit, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(CyanEdit, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(WhiteEdit, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(YellowEdit, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(GreenEdit, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(BlueEdit, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(RedEdit, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(13, 13, 13))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addComponent(theAnimationPane, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(theTPane, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(theTPane, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(theAnimationPane, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

        private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        	if(!run) {
        		theAnimationPane.generate();
        		run = true;
        	}
        	RedEdit.setEnabled(false);
        	BlueEdit.setEnabled(false);
        	GreenEdit.setEnabled(false);
        	YellowEdit.setEnabled(false);
        	WhiteEdit.setEnabled(false);
        	CyanEdit.setEnabled(false);
        	PinkEdit.setEnabled(false);
        	OrangeEdit.setEnabled(false);
        	frozen = false;
            startAnimation();
            
        }//GEN-LAST:event_jButton1ActionPerformed

        private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        	frozen = true;
            stopAnimation();
            
        }//GEN-LAST:event_jButton2ActionPerformed

        private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        	int fps = 0;

    		// How many milliseconds between frames?
    		int delay = (fps > 0) ? (1000 / fps) : 100;

    		// Set up a timer that calls this object's action handler.
    		timer.stop();
    		timer = new Timer(delay, this);
    		timer.setInitialDelay(0);
    		timer.setCoalesce(true);
    		RedEdit.setEnabled(true);
        	BlueEdit.setEnabled(true);
        	GreenEdit.setEnabled(true);
        	YellowEdit.setEnabled(true);
        	WhiteEdit.setEnabled(true);
        	CyanEdit.setEnabled(true);
        	PinkEdit.setEnabled(true);
        	OrangeEdit.setEnabled(true);
        	int arr[] = new int[15];
            for(int i=0;i<15;i++) {
            	arr[i] = i-7;
            }
            BlueEdit.setText(""+arr[(int)(Math.random()*15)]);

            RedEdit.setText(""+arr[(int)(Math.random()*15)]);

            WhiteEdit.setText(""+arr[(int)(Math.random()*15)]);

            CyanEdit.setText(""+arr[(int)(Math.random()*15)]);

            YellowEdit.setText(""+arr[(int)(Math.random()*15)]);

            GreenEdit.setText(""+arr[(int)(Math.random()*15)]);

            OrangeEdit.setText(""+arr[(int)(Math.random()*15)]);

            PinkEdit.setText(""+arr[(int)(Math.random()*15)]);
        	theAnimationPane.reset();
        	theAnimationPane.repaint();
        	GameViz.indent = 0;
        	theTPane.repaint();
        }//GEN-LAST:event_jButton3ActionPerformed

	/**
	 * @param args
	 *            the command line arguments
	 */
	public static void main(String args[]) {
		java.awt.EventQueue.invokeLater(new Runnable() {

			public void run() {
				MainFrame thing = new MainFrame();
				thing.setVisible(true);
				thing.initComponents();
				//startAnimation();
			}
		});
	}

	public synchronized static void startAnimation() {
		if (frozen) {
			// Do nothing. The user has requested that we
			// stop changing the image.
		} else {
			// Start animating!
			if (!timer.isRunning()) {
				timer.start();
			}
		}
	}

	// Can be invoked from any thread.
	public synchronized static void stopAnimation() {
		// Stop the animating thread.
		System.out.println(timer.isRunning());
		if (timer.isRunning()) {
			timer.stop();
		}
	}

	public void actionPerformed(ActionEvent e) {
		// Advance animation frame.
		if (AnimationPane.frameNumber < 100) {
			if (Game.expires.contains(AnimationPane.frameNumber)) {
				System.out.println(theAnimationPane.kt.updateWinner().color);
			}
			AnimationPane.frameNumber++;
			theTPane.repaint();
			// Display it.

			theAnimationPane.repaint();
		} else {
			((AnimationPane) theAnimationPane).reset();
			
		}

	}

    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JTextField BlueEdit;
    public javax.swing.JTextField CyanEdit;
    public javax.swing.JTextField GreenEdit;
    public javax.swing.JTextField OrangeEdit;
    public javax.swing.JTextField PinkEdit;
    public javax.swing.JTextField RedEdit;
    public javax.swing.JTextField WhiteEdit;
    public javax.swing.JTextField YellowEdit;
    public javax.swing.JButton jButton1;
    public javax.swing.JButton jButton2;
    public javax.swing.JButton jButton3;
    public javax.swing.JLabel jLabel1;
    public javax.swing.JLabel jLabel2;
    public javax.swing.JLabel jLabel3;
    public javax.swing.JLabel jLabel4;
    public javax.swing.JLabel jLabel5;
    public javax.swing.JLabel jLabel6;
    public javax.swing.JLabel jLabel7;
    public javax.swing.JLabel jLabel8;
    public javax.swing.JLabel jLabel9;
    public javax.swing.JPanel theTPane;
    // End of variables declaration//GEN-END:variables
}
